package com.wtm.spring_boot_wtm.model;

import lombok.Data;
import java.time.LocalDateTime;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Data // Lombok will generate getters, setters, equals, hashCode, and toString methods automatically
@Table(name="users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // This field will have the default getter and setter generated by Lombok

    @Column(name = "firstname")
    private String firstname;

    @Column(name = "lastname")
    private String lastname;

    @Column(name = "email", unique = true)
    private String email;

    @Column(name = "username", unique = true)
    private String username;  // Lombok will generate the getter and setter

    @Column(name = "password")
    private String password;  // Lombok will generate the getter and setter

    @Column(name = "age")
    private Integer age;

    @Column(name = "create_time")
    private LocalDateTime createTime;

    // Custom setter for createTime field as it is not auto-generated by Lombok
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }
}